name: CI/CD test for sprint 4 

# pulls from the 'main' branch which is where the project is stored
on: 
  pull_request:
    branches:
      main


# tells it to install and run the latest version of ubuntu as well as the to install Node JS
jobs: 
  test: 
    runs- on: ubuntu-latest
      container:
        image: node20
      

      ste
