name: CI/CD test for sprint 4 

# pulls from the 'main' branch which is where the project is stored
on: 
  pull_request:
    branches:
      main


# tells it to install and run the latest version of ubuntu as well as the to install NodeJS
jobs: 
  test: 
    runs- on: ubuntu-latest
    container:
        image: node20
      
# adding code to virtual enviroment using latest verion of NodeJS
      steps: 
        - uses: actions/checkout@v3
          with:
            node-version: 20

 
# builds to the dependencies used in the build such as npm install and docker-compose up. Then npm run build, to build and run the code
        - run: npm install
        - run: docker-compose up
        - run: npm run build
        
