name: Auto deploy

# code is the same as CD-test.yml

on: 
  push:
    branches:
      - main



jobs: 
  deploy:  
    runs-on: ubuntu-latest
    container:
        image: node20
      steps:
        - uses: actions/checkout@v3
          with: 
            node-version: 20
        - run: npm install
        - run: npm docker-compose up
        - run: docker run build 
        


        